// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: src/resource.proto

package resourcepb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	types "github.com/naoto0822/k8s-playground/proto/go/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetSobaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSobaRequest) Reset() {
	*x = GetSobaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_resource_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSobaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSobaRequest) ProtoMessage() {}

func (x *GetSobaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_resource_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSobaRequest.ProtoReflect.Descriptor instead.
func (*GetSobaRequest) Descriptor() ([]byte, []int) {
	return file_src_resource_proto_rawDescGZIP(), []int{0}
}

type GetSobaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sobas []*types.Soba `protobuf:"bytes,1,rep,name=sobas,proto3" json:"sobas,omitempty"`
}

func (x *GetSobaResponse) Reset() {
	*x = GetSobaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_resource_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSobaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSobaResponse) ProtoMessage() {}

func (x *GetSobaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_resource_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSobaResponse.ProtoReflect.Descriptor instead.
func (*GetSobaResponse) Descriptor() ([]byte, []int) {
	return file_src_resource_proto_rawDescGZIP(), []int{1}
}

func (x *GetSobaResponse) GetSobas() []*types.Soba {
	if x != nil {
		return x.Sobas
	}
	return nil
}

var File_src_resource_proto protoreflect.FileDescriptor

var file_src_resource_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x72, 0x63, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x70, 0x62,
	0x1a, 0x0f, 0x73, 0x72, 0x63, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x10, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x62, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x34, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x62, 0x61, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x73, 0x6f, 0x62, 0x61, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x53, 0x6f,
	0x62, 0x61, 0x52, 0x05, 0x73, 0x6f, 0x62, 0x61, 0x73, 0x32, 0x59, 0x0a, 0x0f, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0b,
	0x47, 0x65, 0x74, 0x53, 0x6f, 0x62, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x62, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x62, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6e, 0x61, 0x6f, 0x74, 0x6f, 0x30, 0x38, 0x32, 0x32, 0x2f, 0x6b, 0x38, 0x73,
	0x2d, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x67, 0x6f, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_resource_proto_rawDescOnce sync.Once
	file_src_resource_proto_rawDescData = file_src_resource_proto_rawDesc
)

func file_src_resource_proto_rawDescGZIP() []byte {
	file_src_resource_proto_rawDescOnce.Do(func() {
		file_src_resource_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_resource_proto_rawDescData)
	})
	return file_src_resource_proto_rawDescData
}

var file_src_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_resource_proto_goTypes = []interface{}{
	(*GetSobaRequest)(nil),  // 0: resourcepb.GetSobaRequest
	(*GetSobaResponse)(nil), // 1: resourcepb.GetSobaResponse
	(*types.Soba)(nil),      // 2: types.Soba
}
var file_src_resource_proto_depIdxs = []int32{
	2, // 0: resourcepb.GetSobaResponse.sobas:type_name -> types.Soba
	0, // 1: resourcepb.ResourceService.GetSobaList:input_type -> resourcepb.GetSobaRequest
	1, // 2: resourcepb.ResourceService.GetSobaList:output_type -> resourcepb.GetSobaResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_resource_proto_init() }
func file_src_resource_proto_init() {
	if File_src_resource_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_resource_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSobaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_resource_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSobaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_resource_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_resource_proto_goTypes,
		DependencyIndexes: file_src_resource_proto_depIdxs,
		MessageInfos:      file_src_resource_proto_msgTypes,
	}.Build()
	File_src_resource_proto = out.File
	file_src_resource_proto_rawDesc = nil
	file_src_resource_proto_goTypes = nil
	file_src_resource_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ResourceServiceClient is the client API for ResourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResourceServiceClient interface {
	GetSobaList(ctx context.Context, in *GetSobaRequest, opts ...grpc.CallOption) (*GetSobaResponse, error)
}

type resourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceServiceClient(cc grpc.ClientConnInterface) ResourceServiceClient {
	return &resourceServiceClient{cc}
}

func (c *resourceServiceClient) GetSobaList(ctx context.Context, in *GetSobaRequest, opts ...grpc.CallOption) (*GetSobaResponse, error) {
	out := new(GetSobaResponse)
	err := c.cc.Invoke(ctx, "/resourcepb.ResourceService/GetSobaList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceServiceServer is the server API for ResourceService service.
type ResourceServiceServer interface {
	GetSobaList(context.Context, *GetSobaRequest) (*GetSobaResponse, error)
}

// UnimplementedResourceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedResourceServiceServer struct {
}

func (*UnimplementedResourceServiceServer) GetSobaList(context.Context, *GetSobaRequest) (*GetSobaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSobaList not implemented")
}

func RegisterResourceServiceServer(s *grpc.Server, srv ResourceServiceServer) {
	s.RegisterService(&_ResourceService_serviceDesc, srv)
}

func _ResourceService_GetSobaList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSobaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetSobaList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resourcepb.ResourceService/GetSobaList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetSobaList(ctx, req.(*GetSobaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ResourceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resourcepb.ResourceService",
	HandlerType: (*ResourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSobaList",
			Handler:    _ResourceService_GetSobaList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/resource.proto",
}
