apiVersion: v1
kind: Service
metadata:
  name: processor-app-service
  labels:
    app: processor-app
spec:
  selector:
    app: processor-app
  ports:
  - name: grpc
    protocol: TCP
    port: 10002
    targetPort: 10002
