apiVersion: v1
kind: Service
metadata:
  name: resource-app-service
  labels:
    app: resource-app
spec:
  selector:
    app: resource-app
  ports:
  - name: grpc
    protocol: TCP
    port: 10003
    targetPort: 10003
